name: k6-auth-login # Specify your workflow name

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Choose the runner"
        type: choice
        required: false
        default: "self-hosted"
        options:
          - "self-hosted"
      file_path:
        description: 'File Path'
        required: true
        default: '/src\tests\auth-login.js'
        type: choice
        options:
          - '/src\tests\auth-login.js'
      vus:
        description: "Number of pre-allocated VUs"
        required: true
        default: "1"
      ramping_up_rate:
        description: "Ramping up rate (requests per second)"
        required: true
        default: "10"
      stay_rate:
        description: "Stay rate (requests per second)"
        required: true
        default: "5"
      ramping_down_rate:
        description: "Ramping down rate (requests per second)"
        required: true
        default: "0"
      ramping_up_time:
        description: "Duration for ramping up"
        required: true
        default: "10s"
      stay_time:
        description: "Duration for staying at the stay rate"
        required: true
        default: "30s"
      ramping_down_time:
        description: "Duration for ramping down"
        required: true
        default: "10s"

jobs:
  run-k6-test:
    runs-on: "${{ github.event.inputs.runner }}"
    steps:
      - name: auth-login
        uses: actions/checkout@v2
        
      - name: Run k6 load test
        run: |
          k6 run --insecure-skip-tls-verify ${{ github.event.inputs.file_path }}
        env:
          VUS: "${{ github.event.inputs.vus }}"  
          RAMPING_UP_RATE: "${{ github.event.inputs.ramping_up_rate }}"
          STAY_RATE: "${{ github.event.inputs.stay_rate }}"
          RAMPING_DOWN_RATE: "${{ github.event.inputs.ramping_down_rate }}"
          RAMPING_UP_TIME: "${{ github.event.inputs.ramping_up_time }}"
          STAY_TIME: "${{ github.event.inputs.stay_time }}"
          RAMPING_DOWN_TIME: "${{ github.event.inputs.ramping_down_time }}"